name: Lint

on:
  push:
    branches: [main, v3]
  pull_request:
    branches: [main, v3]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Lint
        run: deno lint